---
- name: install apache
  hosts: webserver
  remote_user: ansible
  become: true
  vars:
   index_src: files/index.html 
  tasks:
    - name: httpd installed
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: custom index.html
      ansible.builtin.copy:
        src: "{{ index_src }}"
        dest: /var/www/html/index.html
    - name: httpd service enabled
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started
#    - name: open firewall
#      ansible.posix.firewalld:
#        service: http
#        state: enabled
#        immediate: true
#        permanent: true
