---
- name: install apache
  hosts: webserver
  become: true
  vars:
   index_src: files/index.html
  tasks:
    - name: httpd installed
      yum:
        name: httpd
        state: latest
    - name: custom index.html
      template:
        src: "{{ index_src }}"
        dest: /var/www/html/index.html
      notify:
       - restart httpd
    - name: httpd service enabled
      service:
        name: httpd
        enabled: true
        state: started
#    - name: Import firewall task
#      import_tasks: tasks/firewall.yml
#        rule:
#        - http
#        - https
#    - name: firewalld service enabled
#      service:
#        name: firewalld
#        enabled: true
#        state: started
#    - name: open ports 80 and 443
#      firewalld:
#        service: http
#        state: enabled
#        immediate: true
#        permanent: true
#      rule:
#       - http
#       - https

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
