---
- name: Install the firewall
  yum:
    name: firewalld
    state: latest

- name: Start the firewall
  service:
    name: firewalld
    enabled: true
    state: started

- name: Open the ports firewalld
  firewalld:
    service: firewalld
    immediate: true
    permanent: true
    state: enabled
#    loop: "{{ rule }}"
    loop:
      - http
      - https
